### ISSUE TITLE
How can I play Pong_no_frameskip_v4 with RainbowIQN?

### ISSUE THREAD

**Issue by jsrimr** [medipixel/rl_algorithms#169]
I'd like to play pong with rainbow IQN algorithms, but the repository provides only dqn. How can I play RainbowIQN?

**Comment by MrSyee** [comment]
Hi @jsrimr 

We implemented RainbowIQN as default when it plays DQN on the Atari Pong environment because IQN is a distributional form of DQN and it shows the best performance on this environment. When you play pong this command below, agent is trained by Rainbow IQN algorithm:
```
python run_pong_no_frameskip_v4.py --algo dqn
```

If you change the configuration of DQN, check this [code](https://github.com/medipixel/rl_algorithms/blob/95bc6eaf8440c8e16bff59c96e24ebe778471130/examples/pong_no_frameskip_v4/dqn.py#L47).

**Comment by jsrimr** [comment]
@Mrsyee Thank you for your reply! I waited for several minutes but to observe the poor performance.. So I assumed the algorithm was simple dqn but it's highly likely problem lies on my part..
