### ISSUE TITLE
question on performance (to speed up training time)

### ISSUE THREAD

**Issue by junhuang-ifast** [medipixel/rl_algorithms#189]
Hi, I am running one instance of [Rainbow DQN](https://github.com/medipixel/rl_algorithms/tree/master/rl_algorithms/dqn) out of the box (without any changes to architecture or model layers) on:
CPU - Intel i7-8700 3.20GHz (6 cores)
GPU - GeForce RTX 2080 (1 gpu)

The Rainbow DQN seems to be mostly using the CPU only (up to 70% utilisation) while only using less than 0.5 GB GPU memory. Is this normal?

I think since the out of the box Rainbow DQN uses only a few Linear layers, it won't use much GPU, if this is the case, can more tensors from other operations like prioritised replay memory ...etc be moved to the GPU? 

I am not an expert so I am not sure what should/should not be placed on the tensor (in terms of efficiency), but basically my thinking is that if more tensors/operations can be moved onto the GPU, it'll speed up training time? Or maybe this is the standard way of placing tensors/operations in Rainbow DQN?

Any clarification/suggestions on if its possible to speed up training time, if so how (without additional hardware) would be much appreciated :)

**Comment by Curt-Park** [comment]
As you pointed out, Rainbow-DQN doesn't utilize GPU much because it only employs shallow FC layers. Even if you optimize the replay buffer by reducing the CPU-GPU bottleneck, mostly it wouldn't be so effective because of the agent-environment interaction time; Mostly, the overall bottleneck occurs in agent-environment interactions. Of course, it will depend on the environment you use though.

By the way, if you want to move Replay memory on GPU, firstly you should concern the bottleneck in ADDing transitions, which are returned by env, from CPU to GPU every step. I hope the following idea would be helpful for you.
- https://arxiv.org/pdf/1801.03138.pdf
- https://github.com/bparr/gpu-experience-replay

The idea is simple. It defines a fixed size of a block and updates the block in GPU memory when it is full. 
>  The experience replay Variable is partitioned into contiguous blocks of equal size, which is denoted as the "update-size". Experiences are queued in RAM until the queue has enough experiences to update the next block. Then the first update-size experiences in the queue are copied to the next update block in the GPU memory using the TensorFlow scatter_update function.

**Comment by junhuang-ifast** [comment]
hmm interesting i'll take a look thanks !
