### ISSUE TITLE
Loaded pretrained model does not converge quickly

### ISSUE THREAD

**Issue by ahmedabuelnasr** [medipixel/rl_algorithms#321]
I trained a SAC agent on a custom environment and the agent behaves well and by the final episode the agent is converging quickly (in a low number of steps) towards the target objectives. 

when I save the trained agent and load it and start training again (agent.train()) the agent takes a long time to converge again towards the target objectives ( as if it is being trained from scratch). 
shouldn't the agent continue training as if it was stopped at the final episode?
I am using lunar lander continuous V2 main script and SACLearner as the RL agent

**Comment by jiseongHAN** [comment]
Hello, Thanks for using our repo.

In SAC, we are using initial random action for exploration.([here](https://github.com/medipixel/rl_algorithms/blob/96bceb9d65c6d66fca59c4115cd7947f87b87ebc/configs/lunarlander_continuous_v2/sac.yaml#L7) and [here](https://github.com/medipixel/rl_algorithms/blob/96bceb9d65c6d66fca59c4115cd7947f87b87ebc/rl_algorithms/sac/agent.py#L115-L119))
That's why pre-trained model seems like not successfully loaded in train phase.

You can change initial random action config as 0 to train your agent without exploration.

**Comment by ahmedabuelnasr** [comment]
Hello, Thanks a lot for you answer, that seems to be the issue, changing the initial random action to 0 in config solved the problem.
